### This code Generate a Corresponding Node index for OSMID on the edge Dataset

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Load the node data from OpenStreetMap

In [3]:
# Load the node data from OpenStreetMap
nodes = pd.read_csv('Kentucky_nodes.csv')
nodes

       node_index       osm_id  is_stop_only      pos_x      pos_y
0               0     53726295         False -88.326025  36.500498
1               1    161654014         False -88.952658  36.988818
2               2    161654295         False -88.861911  37.005113
3               3    161654312         False -88.852288  37.005185
4               4    161656958         False -89.088654  36.968693
...           ...          ...           ...        ...        ...
12848       12848  12162675984         False -84.196913  37.214252
12849       12849  12162675985         False -84.196979  37.214069
12850       12850  12164599414         False -82.642581  37.178470
12851       12851  12193157156         False -84.237006  36.853901
12852       12852  12350931648         False -83.690768  36.697666

[12853 rows x 5 columns]

## Create Node Dictionary

In [4]:
node_lookup = dict(zip(nodes['osm_id'], nodes['node_index']))
node_lookup

{53726295: 0,
 161654014: 1,
 161654295: 2,
 161654312: 3,
 161656958: 4,
 161666993: 5,
 161684907: 6,
 161684937: 7,
 161707908: 8,
 161710257: 9,
 161710276: 10,
 161710286: 11,
 161710317: 12,
 161711344: 13,
 161714437: 14,
 161718371: 15,
 162511352: 16,
 162514902: 17,
 162514931: 18,
 162516253: 19,
 162516371: 20,
 162516388: 21,
 162516398: 22,
 162516417: 23,
 162516562: 24,
 162516625: 25,
 162518402: 26,
 162518423: 27,
 162518428: 28,
 162518445: 29,
 162518481: 30,
 162518513: 31,
 162518564: 32,
 162518579: 33,
 162518582: 34,
 162518602: 35,
 162518634: 36,
 162520310: 37,
 162520349: 38,
 162520432: 39,
 162520449: 40,
 162520511: 41,
 162520539: 42,
 162520823: 43,
 162521510: 44,
 162521555: 45,
 162521582: 46,
 162521616: 47,
 162521651: 48,
 162521688: 49,
 162521821: 50,
 162522497: 51,
 162522543: 52,
 162523374: 53,
 162523421: 54,
 162524241: 55,
 162524351: 56,
 162526961: 57,
 162526976: 58,
 162526997: 59,
 162527054: 60,
 162528779: 61,
 162528793: 62,
 162532696: 63,
 162538019: 64,
 162538022: 65,
 162538529: 66,
 162538545: 67,
 162540409: 68,
 162540675: 69,
 162546405: 70,
 162549100: 71,
 162551575: 72,
 162551816: 73,
 162556715: 74,
 162556717: 75,
 162556757: 76,
 162557700: 77,
 162557941: 78,
 162559561: 79,
 162575306: 80,
 162575368: 81,
 162577780: 82,
 162577786: 83,
 162579654: 84,
 162585121: 85,
 162586463: 86,
 162586815: 87,
 162588448: 88,
 162588477: 89,
 162588662: 90,
 162589005: 91,
 162589007: 92,
 162592468: 93,
 162593826: 94,
 162599762: 95,
 162602489: 96,
 162604625: 97,
 162606653: 98,
 162610161: 99,
 162616256: 100,
 162617996: 101,
 162619831: 102,
 162619851: 103,
 162620169: 104,
 162620176: 105,
 162620177: 106,
 162620441: 107,
 162620615: 108,
 162620620: 109,
 162620629: 110,
 162620662: 111,
 162620832: 112,
 162620857: 113,
 162628074: 114,
 162629710: 115,
 162629807: 116,
 162630668: 117,
 162630752: 118,
 162632033: 119,
 162632085: 120,
 162634078: 121,
 162636731: 122,
 162638040: 123,
 162638371: 124,
 162639028: 125,
 162642814: 126,
 162646031: 127,
 162646270: 128,
 162650770: 129,
 162652304: 130,
 162653668: 131,
 162653723: 132,
 162653726: 133,
 162653758: 134,
 162653785: 135,
 162653914: 136,
 162654151: 137,
 162659393: 138,
 162660088: 139,
 162683906: 140,
 162697149: 141,
 162697161: 142,
 162920175: 143,
 162920883: 144,
 162920932: 145,
 162920934: 146,
 162921548: 147,
 162923355: 148,
 162923393: 149,
 162923476: 150,
 162925405: 151,
 162925432: 152,
 162925471: 153,
 162925521: 154,
 162925526: 155,
 162929673: 156,
 162930580: 157,
 162930583: 158,
 162930589: 159,
 162930671: 160,
 162930765: 161,
 162930776: 162,
 162930777: 163,
 162930812: 164,
 162932418: 165,
 162932422: 166,
 162932437: 167,
 162932741: 168,
 162936426: 169,
 162936455: 170,
 162936604: 171,
 162937912: 172,
 162937984: 173,
 162938066: 174,
 162938082: 175,
 162938304: 176,
 162938308: 177,
 162943936: 178,
 162943968: 179,
 162943978: 180,
 162951720: 181,
 162951738: 182,
 162951794: 183,
 162951798: 184,
 162951908: 185,
 162951927: 186,
 162951960: 187,
 162954360: 188,
 162954426: 189,
 162954443: 190,
 162954454: 191,
 162956267: 192,
 162956306: 193,
 162956313: 194,
 162956318: 195,
 162956437: 196,
 162957433: 197,
 162957458: 198,
 162957478: 199,
 162959458: 200,
 162959543: 201,
 162959619: 202,
 162959678: 203,
 162959709: 204,
 162959746: 205,
 162961924: 206,
 162961946: 207,
 162963195: 208,
 162964154: 209,
 162964156: 210,
 162964163: 211,
 162964165: 212,
 162964172: 213,
 162964174: 214,
 162965300: 215,
 162965304: 216,
 162965764: 217,
 162965785: 218,
 162965808: 219,
 162965872: 220,
 162967856: 221,
 162967862: 222,
 162967868: 223,
 162967928: 224,
 162967938: 225,
 162967942: 226,
 162968849: 227,
 162968874: 228,
 162968876: 229,
 162969478: 230,
 162969495: 231,
 162975455: 232,
 162975488: 233,
 162976761: 234,
 162978919: 235,
 162978921: 236,
 162979630: 237,
 162979648: 238,
 162979740: 239,
 162980312: 240,
 162980374: 241,
 162980424: 242,
 162980445: 243,
 162980620: 244,
 162980630: 245,
 162982422: 246,
 162982484: 247,
 162982510: 248,
 162984818: 249,
 162984819: 250,
 162984826: 251,
 162987356: 252,
 162989314: 253,
 162989316: 254,
 162989450: 255,
 162989463: 256,
 162993321: 257,
 162997770: 258,
 163000825: 259,
 163006597: 260,
 163007974: 261,
 163007989: 262,
 163008008: 263,
 163008017: 264,
 163008036: 265,
 163008044: 266,
 163008056: 267,
 163008162: 268,
 163008176: 269,
 163009650: 270,
 163009961: 271,
 163009964: 272,
 163010051: 273,
 163013848: 274,
 163014382: 275,
 163017855: 276,
 163019186: 277,
 163019193: 278,
 163019331: 279,
 163020333: 280,
 163020536: 281,
 163020571: 282,
 163020734: 283,
 163020736: 284,
 163022057: 285,
 163024258: 286,
 163025595: 287,
 163025631: 288,
 163025634: 289,
 163025870: 290,
 163025886: 291,
 163026046: 292,
 163026052: 293,
 163026576: 294,
 163026635: 295,
 163028937: 296,
 163030883: 297,
 163031232: 298,
 163032560: 299,
 163032609: 300,
 163032813: 301,
 163032846: 302,
 163032858: 303,
 163033026: 304,
 163033063: 305,
 163033325: 306,
 163033513: 307,
 163033787: 308,
 163034501: 309,
 163034508: 310,
 163034723: 311,
 163035279: 312,
 163036494: 313,
 163036652: 314,
 163042621: 315,
 163043014: 316,
 163043020: 317,
 163044542: 318,
 163044870: 319,
 163052947: 320,
 163055323: 321,
 163056428: 322,
 163056449: 323,
 163056452: 324,
 163056462: 325,
 163056549: 326,
 163056552: 327,
 163056998: 328,
 163057664: 329,
 163057853: 330,
 163061816: 331,
 163062268: 332,
 163062317: 333,
 163062320: 334,
 163062431: 335,
 163062737: 336,
 163062745: 337,
 163063834: 338,
 163064253: 339,
 163064393: 340,
 163064399: 341,
 163064541: 342,
 163065095: 343,
 163066027: 344,
 163066219: 345,
 163066222: 346,
 163067999: 347,
 163068140: 348,
 163068173: 349,
 163068329: 350,
 163069393: 351,
 163071799: 352,
 163071958: 353,
 163072619: 354,
 163072653: 355,
 163073897: 356,
 163073928: 357,
 163074004: 358,
 163079148: 359,
 163079251: 360,
 163080302: 361,
 163080409: 362,
 163080480: 363,
 163080483: 364,
 163085433: 365,
 163087286: 366,
 163087350: 367,
 163087468: 368,
 163096074: 369,
 163096491: 370,
 163096865: 371,
 163096955: 372,
 163100446: 373,
 163100478: 374,
 163104382: 375,
 163104646: 376,
 163106319: 377,
 163107917: 378,
 163108051: 379,
 163117684: 380,
 163117687: 381,
 163119833: 382,
 163120284: 383,
 163120360: 384,
 163120369: 385,
 163121627: 386,
 163121679: 387,
 163121906: 388,
 163121943: 389,
 163121987: 390,
 163122050: 391,
 163122067: 392,
 163122098: 393,
 163122994: 394,
 163123002: 395,
 163130999: 396,
 163145837: 397,
 163146015: 398,
 163146486: 399,
 163148460: 400,
 163155279: 401,
 163155352: 402,
 163155396: 403,
 163155423: 404,
 163155943: 405,
 163156249: 406,
 163156337: 407,
 163156395: 408,
 163158017: 409,
 163158019: 410,
 163158222: 411,
 163158718: 412,
 163158804: 413,
 163160438: 414,
 163160468: 415,
 163162767: 416,
 163166206: 417,
 163167501: 418,
 163169931: 419,
 163174751: 420,
 163184538: 421,
 163190963: 422,
 163200567: 423,
 163203221: 424,
 163204490: 425,
 163204962: 426,
 163231161: 427,
 163231325: 428,
 163233247: 429,
 163233288: 430,
 163233296: 431,
 163233297: 432,
 163233312: 433,
 163233344: 434,
 163234776: 435,
 163234830: 436,
 163234936: 437,
 163234953: 438,
 163234995: 439,
 163235031: 440,
 163235043: 441,
 163235134: 442,
 163235148: 443,
 163235176: 444,
 163235376: 445,
 163235414: 446,
 163235460: 447,
 163235491: 448,
 163235505: 449,
 163235818: 450,
 163235883: 451,
 163235966: 452,
 163236088: 453,
 163236134: 454,
 163236300: 455,
 163236362: 456,
 163236378: 457,
 163236403: 458,
 163236510: 459,
 163236815: 460,
 163236828: 461,
 163236830: 462,
 163236836: 463,
 163236848: 464,
 163238801: 465,
 163238839: 466,
 163238879: 467,
 163240473: 468,
 163240773: 469,
 163240883: 470,
 163240926: 471,
 163240938: 472,
 163240939: 473,
 163240946: 474,
 163240995: 475,
 163241336: 476,
 163241761: 477,
 163241776: 478,
 163241982: 479,
 163242000: 480,
 163242101: 481,
 163242201: 482,
 163242220: 483,
 163242260: 484,
 163242288: 485,
 163242307: 486,
 163242742: 487,
 163242762: 488,
 163242784: 489,
 163242793: 490,
 163242802: 491,
 163242838: 492,
 163242896: 493,
 163243049: 494,
 163243072: 495,
 163243929: 496,
 163243937: 497,
 163243949: 498,
 163243961: 499,
 163243967: 500,
 163244013: 501,
 163244019: 502,
 163244066: 503,
 163245316: 504,
 163246278: 505,
 163246281: 506,
 163246342: 507,
 163246346: 508,
 163248443: 509,
 163248609: 510,
 163248660: 511,
 163249039: 512,
 163249256: 513,
 163249265: 514,
 163249289: 515,
 163249341: 516,
 163249351: 517,
 163251520: 518,
 163251603: 519,
 163251637: 520,
 163251777: 521,
 163251836: 522,
 163252692: 523,
 163252704: 524,
 163252710: 525,
 163252742: 526,
 163253876: 527,
 163253883: 528,
 163254546: 529,
 163254899: 530,
 163256357: 531,
 163257051: 532,
 163257656: 533,
 163257776: 534,
 163257802: 535,
 163257833: 536,
 163257867: 537,
 163262644: 538,
 163262649: 539,
 163262687: 540,
 163262724: 541,
 163265582: 542,
 163273140: 543,
 163275032: 544,
 163275096: 545,
 163278438: 546,
 163278604: 547,
 163290143: 548,
 163290167: 549,
 163290193: 550,
 163290310: 551,
 163290743: 552,
 163297929: 553,
 163301339: 554,
 163303848: 555,
 163303856: 556,
 163303858: 557,
 163303871: 558,
 163304063: 559,
 163304086: 560,
 163305271: 561,
 163312928: 562,
 163314314: 563,
 163318277: 564,
 163318326: 565,
 163318464: 566,
 163318467: 567,
 163318482: 568,
 163318668: 569,
 163318669: 570,
 163321406: 571,
 163333305: 572,
 163337136: 573,
 163340159: 574,
 163340195: 575,
 163340317: 576,
 163342204: 577,
 163345409: 578,
 163345454: 579,
 163357932: 580,
 163370887: 581,
 163370909: 582,
 163370956: 583,
 163656414: 584,
 163657064: 585,
 163658528: 586,
 163659338: 587,
 163661910: 588,
 163662730: 589,
 163662738: 590,
 163663105: 591,
 163663747: 592,
 163665456: 593,
 163665504: 594,
 163665803: 595,
 163665930: 596,
 163666951: 597,
 163671638: 598,
 163671645: 599,
 163671658: 600,
 163671662: 601,
 163671952: 602,
 163672517: 603,
 163675901: 604,
 163676539: 605,
 163679225: 606,
 163681834: 607,
 163681837: 608,
 163681930: 609,
 163681940: 610,
 163683562: 611,
 163685053: 612,
 163685096: 613,
 163688490: 614,
 163690417: 615,
 163692950: 616,
 163692962: 617,
 163693149: 618,
 163693922: 619,
 163694807: 620,
 163694836: 621,
 163695419: 622,
 163695452: 623,
 163696975: 624,
 163698237: 625,
 163704253: 626,
 163707567: 627,
 163758422: 628,
 163759250: 629,
 163759899: 630,
 163762077: 631,
 163763360: 632,
 163764331: 633,
 163766186: 634,
 163766275: 635,
 163766289: 636,
 163767150: 637,
 163769627: 638,
 163769661: 639,
 163769689: 640,
 163769700: 641,
 163769719: 642,
 163769829: 643,
 163769991: 644,
 163770015: 645,
 163770065: 646,
 163770095: 647,
 163770121: 648,
 163770171: 649,
 163771558: 650,
 163771605: 651,
 163771656: 652,
 163772093: 653,
 163773545: 654,
 163773593: 655,
 163773621: 656,
 163773953: 657,
 163774438: 658,
 163774528: 659,
 163775197: 660,
 163775230: 661,
 163775271: 662,
 163780721: 663,
 163781566: 664,
 163781584: 665,
 163781627: 666,
 163781863: 667,
 163786577: 668,
 163786629: 669,
 163786661: 670,
 163786864: 671,
 163787172: 672,
 163789569: 673,
 163789589: 674,
 163789615: 675,
 163792153: 676,
 163795940: 677,
 163796694: 678,
 163796788: 679,
 163796902: 680,
 163797325: 681,
 163797353: 682,
 163797414: 683,
 163797713: 684,
 163797775: 685,
 163798260: 686,
 163799371: 687,
 163799391: 688,
 163800414: 689,
 163800782: 690,
 163801017: 691,
 163806975: 692,
 163809071: 693,
 163809074: 694,
 163809081: 695,
 163820230: 696,
 163821039: 697,
 163822197: 698,
 163822842: 699,
 163827044: 700,
 163833659: 701,
 163837799: 702,
 163837813: 703,
 163839266: 704,
 163848661: 705,
 163850101: 706,
 163852028: 707,
 163852100: 708,
 163852759: 709,
 163852823: 710,
 163865629: 711,
 163870368: 712,
 163884938: 713,
 163891445: 714,
 163905113: 715,
 163905963: 716,
 163909479: 717,
 163917165: 718,
 163917424: 719,
 163920443: 720,
 163927320: 721,
 163932326: 722,
 163932612: 723,
 163934048: 724,
 163938754: 725,
 163944758: 726,
 163947765: 727,
 163948745: 728,
 163965388: 729,
 163975762: 730,
 163987769: 731,
 163998710: 732,
 164015682: 733,
 164016788: 734,
 164032176: 735,
 164034382: 736,
 164034388: 737,
 164046610: 738,
 164046802: 739,
 164048004: 740,
 164048778: 741,
 164316300: 742,
 164317957: 743,
 164318227: 744,
 164321273: 745,
 164321593: 746,
 164322588: 747,
 164322635: 748,
 164322641: 749,
 164324465: 750,
 164324512: 751,
 164325378: 752,
 164326125: 753,
 164326594: 754,
 164326608: 755,
 164326639: 756,
 164326653: 757,
 164326659: 758,
 164326709: 759,
 164328734: 760,
 164328830: 761,
 164329597: 762,
 164329624: 763,
 164329708: 764,
 164330126: 765,
 164330612: 766,
 164330660: 767,
 164330743: 768,
 164330798: 769,
 164331366: 770,
 164331943: 771,
 164332011: 772,
 164332019: 773,
 164332038: 774,
 164333474: 775,
 164334108: 776,
 164334187: 777,
 164334197: 778,
 164335543: 779,
 164337323: 780,
 164339668: 781,
 164342438: 782,
 164342516: 783,
 164344762: 784,
 164344799: 785,
 164344863: 786,
 164344905: 787,
 164344946: 788,
 164344970: 789,
 164344978: 790,
 164346041: 791,
 164349300: 792,
 164349316: 793,
 164349325: 794,
 164349344: 795,
 164349354: 796,
 164349965: 797,
 164350423: 798,
 164351196: 799,
 164352549: 800,
 164370583: 801,
 164371980: 802,
 164373748: 803,
 164374256: 804,
 164375910: 805,
 164375916: 806,
 164376033: 807,
 164376220: 808,
 164379142: 809,
 164379268: 810,
 164387361: 811,
 164387523: 812,
 164396349: 813,
 164398648: 814,
 164400614: 815,
 164406767: 816,
 164407011: 817,
 164413619: 818,
 164432773: 819,
 164437717: 820,
 164479629: 821,
 164484140: 822,
 164484615: 823,
 164485026: 824,
 164488664: 825,
 164488680: 826,
 164491113: 827,
 164504029: 828,
 164504058: 829,
 164504074: 830,
 164504233: 831,
 164504333: 832,
 164504662: 833,
 164504679: 834,
 164505400: 835,
 164505443: 836,
 164506729: 837,
 164507744: 838,
 164507784: 839,
 164508034: 840,
 164508115: 841,
 164508359: 842,
 164508397: 843,
 164508414: 844,
 164508417: 845,
 164508437: 846,
 164508467: 847,
 164512586: 848,
 164513306: 849,
 164513321: 850,
 164513672: 851,
 164513815: 852,
 164515518: 853,
 164515562: 854,
 164515577: 855,
 164515791: 856,
 164515816: 857,
 164515825: 858,
 164517373: 859,
 164517492: 860,
 164517665: 861,
 164517754: 862,
 164518851: 863,
 164518914: 864,
 164519027: 865,
 164519136: 866,
 164519158: 867,
 164520082: 868,
 164520417: 869,
 164520467: 870,
 164520497: 871,
 164520528: 872,
 164520548: 873,
 164520576: 874,
 164520656: 875,
 164520659: 876,
 164520672: 877,
 164520694: 878,
 164520751: 879,
 164520794: 880,
 164520820: 881,
 164521259: 882,
 164521296: 883,
 164522259: 884,
 164522295: 885,
 164522385: 886,
 164522983: 887,
 164523015: 888,
 164523144: 889,
 164523168: 890,
 164523216: 891,
 164523263: 892,
 164524125: 893,
 164525371: 894,
 164525422: 895,
 164525467: 896,
 164525511: 897,
 164525569: 898,
 164525581: 899,
 164525595: 900,
 164525616: 901,
 164525642: 902,
 164525658: 903,
 164525678: 904,
 164525697: 905,
 164525742: 906,
 164525790: 907,
 164525833: 908,
 164525847: 909,
 164525850: 910,
 164525871: 911,
 164525875: 912,
 164525958: 913,
 164525969: 914,
 164525971: 915,
 164526045: 916,
 164526104: 917,
 164526132: 918,
 164526295: 919,
 164526334: 920,
 164526385: 921,
 164526404: 922,
 164528400: 923,
 164528402: 924,
 164528586: 925,
 164528619: 926,
 164529439: 927,
 164529451: 928,
 164529748: 929,
 164529751: 930,
 164530489: 931,
 164531240: 932,
 164531254: 933,
 164531285: 934,
 164531347: 935,
 164531865: 936,
 164531898: 937,
 164532062: 938,
 164532222: 939,
 164532331: 940,
 164532374: 941,
 164533030: 942,
 164533049: 943,
 164533416: 944,
 164533459: 945,
 164533472: 946,
 164533475: 947,
 164533487: 948,
 164533523: 949,
 164533949: 950,
 164533982: 951,
 164533987: 952,
 164534589: 953,
 164534627: 954,
 164534648: 955,
 164534693: 956,
 164534711: 957,
 164534728: 958,
 164534755: 959,
 164538461: 960,
 164538521: 961,
 164538542: 962,
 164538556: 963,
 164538557: 964,
 164538570: 965,
 164538592: 966,
 164538614: 967,
 164538768: 968,
 164538786: 969,
 164538963: 970,
 164538995: 971,
 164539013: 972,
 164539230: 973,
 164539247: 974,
 164539262: 975,
 164539518: 976,
 164539534: 977,
 164539587: 978,
 164539608: 979,
 164540008: 980,
 164540026: 981,
 164540315: 982,
 164540318: 983,
 164540354: 984,
 164540376: 985,
 164540477: 986,
 164541885: 987,
 164542136: 988,
 164542171: 989,
 164542292: 990,
 164542471: 991,
 164542499: 992,
 164542621: 993,
 164543519: 994,
 164544077: 995,
 164544096: 996,
 164544343: 997,
 164544904: 998,
 164545202: 999,
 ...}

In [5]:
node_lookup[6009457934]

6323

# Load KY edges from OpenStreetMap

In [6]:
# Load KY edges from OpenStreetMap
edges = pd.read_csv('ky_edges_new.csv')
edges

,u,v,key,osmid,ref,name,highway,oneway,reversed,length,...,maxspeed,bridge,junction,tunnel,access,width,area,travelspeed,speed_mps,travel_time
0,53726295,162620662,0,"[16122080, 108852649, 108852550, 16123336]","['KY 893', 'KY 783']","['Stateline Road West', 'Crossland Road', 'Sta...",secondary,False,"[False, True]",10427.517,...,0,NaN,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,686.049742
1,53726295,162616256,0,16122865,US 641;KY 893,Main Street,trunk,False,False,92.744,...,0,NaN,NaN,NaN,NaN,NaN,NaN,53.0,23.69312,3.914385
2,161654014,161707908,0,"[16079888, 16081016]",KY 802,"['Blandville Road', 'La Center Road']",secondary,False,"[False, True]",12059.357,...,0,NaN,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,793.412157
3,161654014,161718371,0,16081447,KY 802,New York Road,secondary,False,True,5803.317,...,0,NaN,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,381.813247
4,161654014,161654295,0,373362864,KY 286,Wickliffe Road,secondary,False,False,8700.246,...,55,NaN,NaN,NaN,NaN,NaN,NaN,44.0,19.66976,442.315819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27642,12193157156,169026464,0,1317432446,NaN,NaN,primary_link,False,True,14.373,...,0,NaN,NaN,NaN,NaN,NaN,NaN,19.0,8.49376,1.692183
27643,12193157156,168837696,0,16381555,KY 90,NaN,primary,False,False,71.579,...,0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,17.88160,4.002942
27644,12193157156,168837775,0,16381555,KY 90,NaN,primary,False,True,432.953,...,0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,17.88160,24.212207
27645,12350931648,161932084,0,1335030195,NaN,NaN,trunk_link,False,True,19.941,...,0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,11.17600,1.784270
27646,12350931648,161848685,0,"[1013334123, 928292877, 241305246]",US 25E,US 25E,trunk,True,False,3134.979,...,0,NaN,NaN,NaN,NaN,NaN,NaN,53.0,23.69312,132.316006

In [7]:
edges = pd.DataFrame(edges)

edges

,u,v,key,osmid,ref,name,highway,oneway,reversed,length,...,maxspeed,bridge,junction,tunnel,access,width,area,travelspeed,speed_mps,travel_time
0,53726295,162620662,0,"[16122080, 108852649, 108852550, 16123336]","['KY 893', 'KY 783']","['Stateline Road West', 'Crossland Road', 'Sta...",secondary,False,"[False, True]",10427.517,...,0,NaN,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,686.049742
1,53726295,162616256,0,16122865,US 641;KY 893,Main Street,trunk,False,False,92.744,...,0,NaN,NaN,NaN,NaN,NaN,NaN,53.0,23.69312,3.914385
2,161654014,161707908,0,"[16079888, 16081016]",KY 802,"['Blandville Road', 'La Center Road']",secondary,False,"[False, True]",12059.357,...,0,NaN,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,793.412157
3,161654014,161718371,0,16081447,KY 802,New York Road,secondary,False,True,5803.317,...,0,NaN,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,381.813247
4,161654014,161654295,0,373362864,KY 286,Wickliffe Road,secondary,False,False,8700.246,...,55,NaN,NaN,NaN,NaN,NaN,NaN,44.0,19.66976,442.315819
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27642,12193157156,169026464,0,1317432446,NaN,NaN,primary_link,False,True,14.373,...,0,NaN,NaN,NaN,NaN,NaN,NaN,19.0,8.49376,1.692183
27643,12193157156,168837696,0,16381555,KY 90,NaN,primary,False,False,71.579,...,0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,17.88160,4.002942
27644,12193157156,168837775,0,16381555,KY 90,NaN,primary,False,True,432.953,...,0,NaN,NaN,NaN,NaN,NaN,NaN,40.0,17.88160,24.212207
27645,12350931648,161932084,0,1335030195,NaN,NaN,trunk_link,False,True,19.941,...,0,NaN,NaN,NaN,NaN,NaN,NaN,25.0,11.17600,1.784270
27646,12350931648,161848685,0,"[1013334123, 928292877, 241305246]",US 25E,US 25E,trunk,True,False,3134.979,...,0,NaN,NaN,NaN,NaN,NaN,NaN,53.0,23.69312,132.316006

In [ ]:
# Create New Columns

In [8]:
# Creates a column with NaN values
edges['from_node'] = None

In [9]:
# Creates a column with NaN values
edges['to_node'] = None

In [10]:
# Rename columns appropriately 
edges = edges.rename(columns={'u': 'from_osm', 'v': 'to_osm', 'length': 'distance', 'osmid': 'source_edge_id', 'highway': 'road_type'})

In [11]:
edges

,from_osm,to_osm,key,source_edge_id,ref,name,road_type,oneway,reversed,distance,...,junction,tunnel,access,width,area,travelspeed,speed_mps,travel_time,from_node,to_node
0,53726295,162620662,0,"[16122080, 108852649, 108852550, 16123336]","['KY 893', 'KY 783']","['Stateline Road West', 'Crossland Road', 'Sta...",secondary,False,"[False, True]",10427.517,...,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,686.049742,NaN,NaN
1,53726295,162616256,0,16122865,US 641;KY 893,Main Street,trunk,False,False,92.744,...,NaN,NaN,NaN,NaN,NaN,53.0,23.69312,3.914385,NaN,NaN
2,161654014,161707908,0,"[16079888, 16081016]",KY 802,"['Blandville Road', 'La Center Road']",secondary,False,"[False, True]",12059.357,...,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,793.412157,NaN,NaN
3,161654014,161718371,0,16081447,KY 802,New York Road,secondary,False,True,5803.317,...,NaN,NaN,NaN,NaN,NaN,34.0,15.19936,381.813247,NaN,NaN
4,161654014,161654295,0,373362864,KY 286,Wickliffe Road,secondary,False,False,8700.246,...,NaN,NaN,NaN,NaN,NaN,44.0,19.66976,442.315819,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27642,12193157156,169026464,0,1317432446,NaN,NaN,primary_link,False,True,14.373,...,NaN,NaN,NaN,NaN,NaN,19.0,8.49376,1.692183,NaN,NaN
27643,12193157156,168837696,0,16381555,KY 90,NaN,primary,False,False,71.579,...,NaN,NaN,NaN,NaN,NaN,40.0,17.88160,4.002942,NaN,NaN
27644,12193157156,168837775,0,16381555,KY 90,NaN,primary,False,True,432.953,...,NaN,NaN,NaN,NaN,NaN,40.0,17.88160,24.212207,NaN,NaN
27645,12350931648,161932084,0,1335030195,NaN,NaN,trunk_link,False,True,19.941,...,NaN,NaN,NaN,NaN,NaN,25.0,11.17600,1.784270,NaN,NaN
27646,12350931648,161848685,0,"[1013334123, 928292877, 241305246]",US 25E,US 25E,trunk,True,False,3134.979,...,NaN,NaN,NaN,NaN,NaN,53.0,23.69312,132.316006,NaN,NaN

In [12]:
# Select only the relevant columns
edges = edges[['from_node', 'to_node', 'from_osm', 'to_osm', 'distance', 'travel_time', 'source_edge_id', 'road_type', 'geometry']]

In [13]:
edges

,from_node,to_node,from_osm,to_osm,distance,travel_time,source_edge_id,road_type,geometry
0,None,None,53726295,162620662,10427.517,686.049742,"[16122080, 108852649, 108852550, 16123336]",secondary,"LINESTRING (-88.3260251 36.5004975, -88.327109..."
1,None,None,53726295,162616256,92.744,3.914385,16122865,trunk,"LINESTRING (-88.3260251 36.5004975, -88.325967..."
2,None,None,161654014,161707908,12059.357,793.412157,"[16079888, 16081016]",secondary,"LINESTRING (-88.9526584 36.9888184, -88.952656..."
3,None,None,161654014,161718371,5803.317,381.813247,16081447,secondary,"LINESTRING (-88.9526584 36.9888184, -88.952660..."
4,None,None,161654014,161654295,8700.246,442.315819,373362864,secondary,"LINESTRING (-88.9526584 36.9888184, -88.952015..."
...,...,...,...,...,...,...,...,...,...
27642,None,None,12193157156,169026464,14.373,1.692183,1317432446,primary_link,"LINESTRING (-84.2370064 36.8539015, -84.236909..."
27643,None,None,12193157156,168837696,71.579,4.002942,16381555,primary,"LINESTRING (-84.2370064 36.8539015, -84.237146..."
27644,None,None,12193157156,168837775,432.953,24.212207,16381555,primary,"LINESTRING (-84.2370064 36.8539015, -84.236957..."
27645,None,None,12350931648,161932084,19.941,1.784270,1335030195,trunk_link,"LINESTRING (-83.6907676 36.6976659, -83.690882..."
27646,None,None,12350931648,161848685,3134.979,132.316006,"[1013334123, 928292877, 241305246]",trunk,"LINESTRING (-83.6907676 36.6976659, -83.690868..."

In [14]:
# Apply the node lookup
edges['from_node'] = edges['from_osm'].apply(lambda x : node_lookup[x])

C:\Users\Musa\AppData\Local\Temp\ipykernel_34804\979919806.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edges['from_node'] = edges['from_osm'].apply(lambda x : node_lookup[x])

In [15]:
# Apply the node lookup
edges['to_node'] = edges['to_osm'].apply(lambda x : node_lookup[x])

C:\Users\Musa\AppData\Local\Temp\ipykernel_34804\1858918885.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  edges['to_node'] = edges['to_osm'].apply(lambda x : node_lookup[x])

In [16]:
edges

,from_node,to_node,from_osm,to_osm,distance,travel_time,source_edge_id,road_type,geometry
0,0,111,53726295,162620662,10427.517,686.049742,"[16122080, 108852649, 108852550, 16123336]",secondary,"LINESTRING (-88.3260251 36.5004975, -88.327109..."
1,0,100,53726295,162616256,92.744,3.914385,16122865,trunk,"LINESTRING (-88.3260251 36.5004975, -88.325967..."
2,1,8,161654014,161707908,12059.357,793.412157,"[16079888, 16081016]",secondary,"LINESTRING (-88.9526584 36.9888184, -88.952656..."
3,1,15,161654014,161718371,5803.317,381.813247,16081447,secondary,"LINESTRING (-88.9526584 36.9888184, -88.952660..."
4,1,2,161654014,161654295,8700.246,442.315819,373362864,secondary,"LINESTRING (-88.9526584 36.9888184, -88.952015..."
...,...,...,...,...,...,...,...,...,...
27642,12851,12258,12193157156,169026464,14.373,1.692183,1317432446,primary_link,"LINESTRING (-84.2370064 36.8539015, -84.236909..."
27643,12851,12168,12193157156,168837696,71.579,4.002942,16381555,primary,"LINESTRING (-84.2370064 36.8539015, -84.237146..."
27644,12851,12169,12193157156,168837775,432.953,24.212207,16381555,primary,"LINESTRING (-84.2370064 36.8539015, -84.236957..."
27645,12852,11194,12350931648,161932084,19.941,1.784270,1335030195,trunk_link,"LINESTRING (-83.6907676 36.6976659, -83.690882..."
27646,12852,11128,12350931648,161848685,3134.979,132.316006,"[1013334123, 928292877, 241305246]",trunk,"LINESTRING (-83.6907676 36.6976659, -83.690868..."

In [17]:
# Check for NaN value in the dataset

edges.isna().any()

from_node         False
to_node           False
from_osm          False
to_osm            False
distance          False
travel_time       False
source_edge_id    False
road_type         False
geometry          False
dtype: bool

In [18]:
# Save edges as a csv
edges.to_csv('Kentucky_edges_enhanced.csv', index=False)